spring.application.name=medcontrol
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
api.security.token.secret=${MEDCONTROL-SECRET}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


